blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/AIToolbox-software/AIToolbox.software/discussions
    about: Join community discussions and share ideas
  - name: 🔗 Website
    url: https://aitoolbox.software
    about: Visit the AIToolbox.software website
  - name: 📧 Contact
    url: mailto:amanraj12.ar@gmail.com
    about: Email us for urgent matters or business inquiries